### ISSUE TITLE
error when activate in the addons from Blender

### ISSUE THREAD

**Issue by manualdomaker** [hgabor47/BLECOLAC-Blender3D-addon-3DPrinter-CNC-Laser-Gcode-generator#12]
Report: Error
Traceback (most recent call last):
  File "/home/alex/blender-3.1.0-linux-x64/3.1/scripts/modules/addon_utils.py", line 351, in enable 
    mod = __import__(module_name)
  File "/home/alex/.conf/blender/3.1/addons/3DPrinterCNC_GCODE_Generator.py", line 56, in <module>

import pip

ModuleNotFoundError: No module named 'pip'

Please, help me
I bought the addons but when installing, it gives me an error.
What do I need to do to get it working?

**Comment by hgabor47** [comment]
Hi,


Thanks your request.


I think you need to run the Blender 3D in administrative mode!

I don't test it in 3.1 yet but tomorrow.

Please send a mail with result.

Thanks Gabor


Alex Costa ***@***.***> ezt írta (időpont: 2022. jún. 4.,
Szo, 23:29):

**Comment by hgabor47** [comment]
Hi, I Installed an Ubuntu system with Blender. I got same error and I make a new version of the Blecolac. I think today you can download it. I close this bug when the patch is out.

**Comment by hgabor47** [comment]
Completed
